[build]
  command = "mvn package"
  functions = "target/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  TOKEN=OTE3MDc0NTQ2OTMzMjYwMzk5.Gcfjds.rXfT-5ctvn1iwN04tTEAU2lTWr7pIKe7vVDvdw